{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7065ae12-0a6c-44b9-9881-b896fef45ec4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "table users already exists\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "from tkinter import *\n",
    "\n",
    "from PIL import Image,ImageTk\n",
    "from tkinter.ttk import Combobox\n",
    "from tkinter import messagebox\n",
    "import sqlite3\n",
    "from tkinter.scrolledtext import ScrolledText\n",
    "from tkinter import filedialog\n",
    "import shutil\n",
    "import os\n",
    "\n",
    "# In[2]:\n",
    "\n",
    "\n",
    "try:\n",
    "    con=sqlite3.connect(database=\"carpool.sqlite\")\n",
    "    cursor=con.cursor()\n",
    "    table1=\"create table users(username text primary key,password text,mobile text,email text)\"\n",
    "    table2=\"create table cars(username text,src text,dest text,regno text primary key,model text,seats text,fuel text)\"\n",
    "    cursor.execute(table1)\n",
    "    cursor.execute(table2)\n",
    "    con.commit()\n",
    "    con.close()\n",
    "    print(\"tables created\")\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "\n",
    "\n",
    "# In[24]:     \n",
    "\n",
    "win=Tk()\n",
    "win.state(\"zoomed\")\n",
    "win.configure(bg=\"white\")\n",
    "lbl_title=Label(win,text=\"CAR POOL SYSTEM\",font=('cambria',40,'bold','underline'),bg=\"white\")\n",
    "lbl_title.pack()\n",
    "\n",
    "img=Image.open(\"images/cp4.jpg\").resize((260,130))\n",
    "imgtk=ImageTk.PhotoImage(img,master=win)\n",
    "lbl_img=Label(win,image=imgtk) #, borderwidth=2, relief=\"solid\")\n",
    "lbl_img.place(relx=.001,rely=0)\n",
    "\n",
    "img2=Image.open(\"images/cp2.jpg\").resize((260,130))\n",
    "imgtk2=ImageTk.PhotoImage(img2,master=win)\n",
    "lbl_img2=Label(win,image=imgtk2) #, borderwidth=2, relief=\"solid\")\n",
    "lbl_img2.place(relx=.804,rely=0)\n",
    "\n",
    "img3=Image.open(\"images/login.png\").resize((120,40))\n",
    "imgtk3=ImageTk.PhotoImage(img3)\n",
    "\n",
    "img4=Image.open(\"images/reset.png\").resize((120,40))\n",
    "imgtk4=ImageTk.PhotoImage(img4)\n",
    "\n",
    "img5=Image.open(\"images/logout.png\").resize((120,40))\n",
    "imgtk5=ImageTk.PhotoImage(img5)\n",
    "\n",
    "img6=Image.open(\"images/register.png\").resize((140,40))\n",
    "imgtk6=ImageTk.PhotoImage(img6)\n",
    "\n",
    "img7=Image.open(\"images/newuser.png\").resize((220,40))\n",
    "imgtk7=ImageTk.PhotoImage(img7)\n",
    "\n",
    "img8=Image.open(\"images/back.png\").resize((120,40))\n",
    "imgtk8=ImageTk.PhotoImage(img8)\n",
    "\n",
    "img9=Image.open(\"images/Search1.png\").resize((120,40))\n",
    "imgtk9=ImageTk.PhotoImage(img9)\n",
    "\n",
    "img10=Image.open(\"images/submit.png\").resize((120,40))\n",
    "imgtk10=ImageTk.PhotoImage(img10)\n",
    "\n",
    "img11=Image.open(\"images/Update.png\").resize((120,40))\n",
    "imgtk11=ImageTk.PhotoImage(img11)\n",
    "\n",
    "img12=Image.open(\"images/profilepic.jpg\").resize((140,140))\n",
    "imgtk12=ImageTk.PhotoImage(img12)\n",
    "\n",
    "\n",
    "def home_frame():\n",
    "    frm=Frame(win,highlightthickness=3,highlightbackground='brown')\n",
    "    frm.place(x=240,y=200,relwidth=.65,relheight=.55)\n",
    "    \n",
    "    def newuser(event):\n",
    "        frm.destroy()\n",
    "        newuser_frame()\n",
    "     \n",
    "    def reset(event):\n",
    "        e_user.delete(0,\"end\")\n",
    "        e_pass.delete(0,\"end\")\n",
    "        e_user.focus()\n",
    "        \n",
    "    def login(event):\n",
    "        global loginuser_row\n",
    "        u=e_user.get()\n",
    "        p=e_pass.get()\n",
    "        try:\n",
    "            con=sqlite3.connect(database=\"carpool.sqlite\")\n",
    "            cursor=con.cursor()\n",
    "            cursor.execute(\"select * from users where username=? and password=?\",(u,p))\n",
    "            loginuser_row=cursor.fetchone()\n",
    "            con.close()\n",
    "            if(loginuser_row==None):\n",
    "                messagebox.showerror(\"Login\",\"Invalid Username/Password\")\n",
    "            else:\n",
    "                \n",
    "                frm.destroy()\n",
    "                login_frame()\n",
    "            \n",
    "        except Exception as e:\n",
    "            messagebox.showerror(\"Login\",str(e))\n",
    "        \n",
    "    lbl_user=Label(frm,text=\"Username\",font=('cambria',15,'bold'))\n",
    "    lbl_pass=Label(frm,text=\"Password\",font=('cambria',15,'bold'))\n",
    "    e_user=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    e_user.focus()\n",
    "    e_pass=Entry(frm,font=('cambria',15,'bold'),bd=3,show=\"*\")\n",
    "    lbl_user.place(x=165,y=50)\n",
    "    e_user.place(x=335,y=50)\n",
    "    lbl_pass.place(x=165,y=130)\n",
    "    e_pass.place(x=335,y=130)\n",
    "    \n",
    "    btn_login=Label(frm,image=imgtk3)\n",
    "    btn_login.place(x=305,y=210)\n",
    "    btn_login.bind(\"<Button>\",login)\n",
    "    \n",
    "    btn_reset=Label(frm,image=imgtk4)\n",
    "    btn_reset.place(x=455,y=210)\n",
    "    btn_reset.bind(\"<Button>\",reset)\n",
    "    \n",
    "    btn_new=Label(frm,image=imgtk7)\n",
    "    btn_new.place(x=336,y=280)\n",
    "    btn_new.bind(\"<Button>\",newuser)\n",
    "\n",
    "    \n",
    "    \n",
    "def newuser_frame():\n",
    "    frm=Frame(win,highlightthickness=3,highlightbackground='brown')\n",
    "    frm.place(x=300,y=200,relwidth=.65,relheight=.55)\n",
    "    \n",
    "        \n",
    "    def reset(event):\n",
    "        e_user.delete(0,\"end\")\n",
    "        e_pass.delete(0,\"end\")\n",
    "        e_mob.delete(0,\"end\")\n",
    "        e_email.delete(0,\"end\")\n",
    "        e_user.focus()\n",
    "        \n",
    "    def reg_todb(event):\n",
    "        u=e_user.get()\n",
    "        p=e_pass.get()\n",
    "        m=e_mob.get()\n",
    "        e=e_email.get()\n",
    "        \n",
    "        if(len(u)==0 or len(p)==0 or len(m)==0 or len(e)==0):\n",
    "            messagebox.showwarning('Validation',\"Please fill all fields!!\")\n",
    "        else:\n",
    "            try:\n",
    "                con=sqlite3.connect(database=\"carpool.sqlite\")\n",
    "                cursor=con.cursor()\n",
    "                cursor.execute(\"insert into users values(?,?,?,?)\",(u,p,m,e))\n",
    "                con.commit()\n",
    "                con.close()\n",
    "                messagebox.showinfo(\"Registration\",\"Registration Done!!\")\n",
    "                frm.destroy()\n",
    "                home_frame()\n",
    "            except Exception as e:\n",
    "                messagebox.showerror(\"Registration\",\"Username already exists!\")\n",
    "                \n",
    "    def back(event):\n",
    "        frm.destroy()\n",
    "        home_frame()\n",
    "\n",
    "    lbl_user=Label(frm,text=\"Username\",font=('cambria',15,'bold'))\n",
    "    lbl_pass=Label(frm,text=\"Password\",font=('cambria',15,'bold'))\n",
    "    lbl_mob=Label(frm,text=\"Mobile\",font=('cambria',15,'bold'))\n",
    "    lbl_email=Label(frm,text=\"Email\",font=('cambria',15,'bold'))\n",
    "    \n",
    "    e_user=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    e_user.focus()\n",
    "    e_pass=Entry(frm,font=('cambria',15,'bold'),bd=3,show=\"*\")\n",
    "    e_mob=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    e_email=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "        \n",
    "    lbl_user.place(x=180,y=80)\n",
    "    e_user.place(x=380,y=80)\n",
    "    lbl_pass.place(x=180,y=140)\n",
    "    e_pass.place(x=380,y=140)\n",
    "    lbl_mob.place(x=180,y=200)\n",
    "    e_mob.place(x=380,y=200)\n",
    "    lbl_email.place(x=180,y=260)\n",
    "    e_email.place(x=380,y=260)\n",
    "\n",
    "    btn_reg=Label(frm,image=imgtk6)\n",
    "    btn_reg.place(x=270,y=320)\n",
    "    btn_reg.bind(\"<Button>\",reg_todb)\n",
    "    \n",
    "    btn_reset=Label(frm,image=imgtk4)\n",
    "    btn_reset.place(x=440,y=320)\n",
    "    btn_reset.bind(\"<Button>\",reset)\n",
    "    \n",
    "    btn_back=Label(frm,image=imgtk8)\n",
    "    btn_back.place(relx=0,rely=.15)\n",
    "    btn_back.bind(\"<Button>\",back)\n",
    "\n",
    "    \n",
    "    \n",
    "    \n",
    "def login_frame():\n",
    "    frm=Frame(win,highlightthickness=3,highlightbackground='brown')\n",
    "    frm.place(x=240,y=200,relwidth=.65,relheight=.55)\n",
    "    \n",
    "    def logout(event):\n",
    "        frm.destroy()\n",
    "        home_frame()\n",
    "        \n",
    "    def search():\n",
    "        frm.destroy()\n",
    "        searchpool_frame()\n",
    "        \n",
    "    def create():\n",
    "        frm.destroy()\n",
    "        createpool_frame()    \n",
    "     \n",
    "    def update():\n",
    "        frm.destroy()\n",
    "        updateprofile_frame()\n",
    "        \n",
    "    def picture():\n",
    "        img_path=filedialog.askopenfilename()\n",
    "        shutil.copy(img_path,f\"images/{loginuser_row[0]}.png\")\n",
    "        img=Image.open(f\"images/{loginuser_row[0]}.png\").resize((140,140))\n",
    "        imgtk=ImageTk.PhotoImage(img)\n",
    "        lbl_profilepic['image']=imgtk\n",
    "        lbl_profilepic.image=imgtk\n",
    "    \n",
    "    lbl_wel=Label(frm,text=f\"Welcome,{loginuser_row[0]}\",font=('cambria',15,'bold'),fg='green')\n",
    "    lbl_wel.place(x=0,y=0)\n",
    "    \n",
    "    lbl_profilepic=Label(frm,image=imgtk12)\n",
    "    lbl_profilepic.place(x=0,y=40)\n",
    "    \n",
    "    if(os.path.exists(f\"images/{loginuser_row[0]}.png\")):\n",
    "        img=Image.open(f\"images/{loginuser_row[0]}.png\").resize((140,140))\n",
    "        imgtk=ImageTk.PhotoImage(img)\n",
    "        lbl_profilepic['image']=imgtk\n",
    "        lbl_profilepic.image=imgtk\n",
    "        \n",
    "    \n",
    "    btn_logout=Label(frm,image=imgtk5)\n",
    "    btn_logout.place(relx=.83,rely=.01)\n",
    "    btn_logout.bind(\"<Button>\",logout)\n",
    "    \n",
    "    btn_search=Button(frm,text=\"Search Pool\",font=('cambria',15,'bold'),bd=3,width=20,command=search)\n",
    "    btn_search.place(relx=.35,rely=.15)\n",
    "    \n",
    "    btn_create=Button(frm,text=\"Create Pool\",font=('cambria',15,'bold'),bd=3,width=20,command=create)\n",
    "    btn_create.place(relx=.35,rely=.35)\n",
    "\n",
    "    btn_profile=Button(frm,text=\"Update Profile\",font=('cambria',15,'bold'),bd=3,width=20,command=update)\n",
    "    btn_profile.place(relx=.35,rely=.55)\n",
    "    \n",
    "    btn_profilepic=Button(frm,text=\"Profile Picture\",font=('cambria',15,'bold'),bd=3,width=20,command=picture)\n",
    "    btn_profilepic.place(relx=.35,rely=.75)\n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "def searchpool_frame():\n",
    "    frm=Frame(win,highlightthickness=3,highlightbackground='brown')\n",
    "    frm.place(x=240,y=200,relwidth=.65,relheight=.55)\n",
    "    \n",
    "    def logout(event):\n",
    "        frm.destroy()\n",
    "        home_frame()\n",
    "        \n",
    "    def back(event):\n",
    "        frm.destroy()\n",
    "        login_frame()\n",
    "    \n",
    "    def searchpool_db(event):\n",
    "        src=e_src.get().upper()\n",
    "        dest=e_dest.get().upper()\n",
    "        \n",
    "        try:\n",
    "            con=sqlite3.connect(database=\"carpool.sqlite\")\n",
    "            cursor=con.cursor()\n",
    "            cursor.execute(\"select * from cars where src=? and dest=?\",(src,dest))\n",
    "            pools=cursor.fetchall()\n",
    "            con.close()\n",
    "            if(len(pools)==0):\n",
    "                messagebox.showerror(\"Pool\",\"Pool does not exist\")\n",
    "            else:\n",
    "                con=sqlite3.connect(database=\"carpool.sqlite\")\n",
    "                cursor=con.cursor()\n",
    "                st=ScrolledText(frm,width=110,height=15,font=('Arial',10,'bold','underline'))\n",
    "                st.place(x=70,y=110)\n",
    "                st.insert(\"end\",\"Username\\t\\tCar Model\\t\\tReg No\\t\\tSeats\\t\\tFuel Type\\t\\tMob\\t\\tEmail\")\n",
    "                \n",
    "                for pool in pools:\n",
    "                    cursor.execute(\"select mobile,email from users where username=?\",(pool[0],))\n",
    "                    m,e=cursor.fetchone()\n",
    "                    st.insert(\"end\",f\"\\n\\n{pool[0]}\\t\\t{pool[4]}\\t\\t{pool[3]}\\t\\t{pool[5]}\\t\\t{pool[6]}\\t\\t{m}\\t\\t{e}\",\"clr\")\n",
    "                    st.tag_config(\"clr\",font=('',10),foreground='blue')\n",
    "                st.configure(state=\"disabled\")\n",
    "                con.close()\n",
    "        except Exception as e:\n",
    "            messagebox.showerror(\"Pool\",str(e))\n",
    "        \n",
    "    lbl_wel=Label(frm,text=f\"Welcome,{loginuser_row[0]}\",font=('',15,'bold'),fg='green')\n",
    "    lbl_wel.place(x=0,y=0)\n",
    "    \n",
    "    btn_logout=Label(frm,image=imgtk5)\n",
    "    btn_logout.place(relx=.83,rely=.01)\n",
    "    btn_logout.bind(\"<Button>\",logout)\n",
    "    \n",
    "    btn_back=Label(frm,image=imgtk8)\n",
    "    btn_back.place(relx=0,rely=.15)\n",
    "    btn_back.bind(\"<Button>\",back)\n",
    "    \n",
    "    lbl_src=Label(frm,text=\"Source\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_src.place(relx=.2,rely=.4)\n",
    "   \n",
    "    e_src=Entry(frm,font=('cambria',15),bd=3,width=14)\n",
    "    e_src.focus()\n",
    "    e_src.place(relx=.29,rely=.4)\n",
    "    \n",
    "    lbl_dest=Label(frm,text=\"Destination\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_dest.place(relx=.51,rely=.4)\n",
    "   \n",
    "    e_dest=Entry(frm,font=('cambria',15),bd=3,width=14)\n",
    "    e_dest.place(relx=.65,rely=.4)\n",
    "    \n",
    "    btn_search=Label(frm,image=imgtk9)\n",
    "    btn_search.place(relx=.45,rely=.64)\n",
    "    btn_search.bind(\"<Button>\",searchpool_db)\n",
    "    \n",
    "    \n",
    "\n",
    "def createpool_frame():\n",
    "    frm=Frame(win,highlightthickness=3,highlightbackground='brown')\n",
    "    frm.place(x=240,y=200,relwidth=.65,relheight=.55)\n",
    "    \n",
    "    def logout(event):\n",
    "        frm.destroy()\n",
    "        home_frame()\n",
    "        \n",
    "    def back(event):\n",
    "        frm.destroy()\n",
    "        login_frame()\n",
    "     \n",
    "    def createpool_db(event):\n",
    "        src=e_src.get()\n",
    "        dest=e_dest.get()\n",
    "        model=e_model.get()\n",
    "        seat=cb_seat.get()\n",
    "        regno=e_regno.get().replace(\" \",\"\")\n",
    "        fueltype=cb_fueltype.get()\n",
    "        \n",
    "        try:\n",
    "                con=sqlite3.connect(database=\"carpool.sqlite\")\n",
    "                cursor=con.cursor()\n",
    "                cursor.execute(\"insert into cars values(?,?,?,?,?,?,?)\",(loginuser_row[0],src.upper(),dest.upper(),regno.upper(),model.upper(),seat,fueltype.upper()))\n",
    "                con.commit()\n",
    "                con.close()\n",
    "                messagebox.showinfo(\"Create Pool\",\"Pool Created Successfully\")\n",
    "                frm.destroy()\n",
    "                login_frame()\n",
    "        except Exception as e:\n",
    "                messagebox.showerror(\"Registration\",\"This car already exists in Pool!\")\n",
    "        \n",
    "    lbl_wel=Label(frm,text=f\"Welcome,{loginuser_row[0]}\",font=('cambria',15,'bold'),fg='green')\n",
    "    lbl_wel.place(x=0,y=0)\n",
    "    \n",
    "    btn_logout=Label(frm,image=imgtk5)\n",
    "    btn_logout.place(relx=.83,rely=.01)\n",
    "    btn_logout.bind(\"<Button>\",logout)\n",
    "    \n",
    "    btn_back=Label(frm,image=imgtk8)\n",
    "    btn_back.place(relx=0,rely=.12)\n",
    "    btn_back.bind(\"<Button>\",back)\n",
    "    \n",
    "    lbl_src=Label(frm,text=\"Source\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_src.place(relx=.19,rely=.22)\n",
    "   \n",
    "    e_src=Entry(frm,font=('',15),bd=3,width=12)\n",
    "    e_src.focus()\n",
    "    e_src.place(relx=.32,rely=.22)\n",
    "    \n",
    "    lbl_dest=Label(frm,text=\"Destination\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_dest.place(relx=.5,rely=.22)\n",
    "   \n",
    "    e_dest=Entry(frm,font=('',15),bd=3,width=17)\n",
    "    e_dest.place(relx=.63,rely=.22)\n",
    "        \n",
    "    lbl_model=Label(frm,text=\"Car Model\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_model.place(relx=.19,rely=.37)\n",
    "    \n",
    "    e_model=Entry(frm,font=('',15),bd=3,width=12)\n",
    "    e_model.place(relx=.32,rely=.37)\n",
    "    \n",
    "    lbl_seat=Label(frm,text=\"Seats\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_seat.place(relx=.5,rely=.37)\n",
    "    \n",
    "    cb_seat=Combobox(frm,values=[2,3,4,5,6,7],font=('cambria',12,'bold'))\n",
    "    cb_seat.current(3)\n",
    "    cb_seat.place(relx=.62,rely=.37)\n",
    "    \n",
    "    lbl_regno=Label(frm,text=\"Car Reg No\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_regno.place(relx=.19,rely=.52)\n",
    "    \n",
    "    e_regno=Entry(frm,font=('',15),bd=3,width=12)\n",
    "    e_regno.place(relx=.32,rely=.52)\n",
    "    \n",
    "    lbl_fueltype=Label(frm,text=\"Fuel Type\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_fueltype.place(relx=.5,rely=.52)\n",
    "    \n",
    "    cb_fueltype=Combobox(frm,values=['Petrol','Diesel','Petrol+CNG','Petrol+LPG','Electric'],font=('',12,'bold'))\n",
    "    cb_fueltype.current(0)\n",
    "    cb_fueltype.place(relx=.62,rely=.52)\n",
    "    \n",
    "    btn_submit=Label(frm,image=imgtk10)\n",
    "    btn_submit.place(relx=.34,rely=.8)\n",
    "    btn_submit.bind(\"<Button>\",createpool_db)\n",
    "    \n",
    "    btn_reset=Label(frm,image=imgtk4)\n",
    "    btn_reset.place(relx=.52,rely=.8)\n",
    "    \n",
    "\n",
    "def updateprofile_frame():\n",
    "    frm=Frame(win,highlightthickness=3,highlightbackground='brown')\n",
    "    frm.place(x=240,y=200,relwidth=.65,relheight=.55)\n",
    "    def logout(event):\n",
    "        frm.destroy()\n",
    "        home_frame()\n",
    "        \n",
    "    def back(event):\n",
    "        frm.destroy()\n",
    "        login_frame()\n",
    "        \n",
    "    def update_todb(event):\n",
    "        u=e_user.get()\n",
    "        p=e_pass.get()\n",
    "        m=e_mob.get()\n",
    "        e=e_email.get()\n",
    "        \n",
    "        con=sqlite3.connect(database=\"carpool.sqlite\")\n",
    "        cursor=con.cursor()\n",
    "        cursor.execute(\"update users set password=?,mobile=?,email=? where username=?\",(p,m,e,u))\n",
    "        con.commit()\n",
    "        con.close()\n",
    "        messagebox.showinfo(\"Update Profile\",\"Record updated\")\n",
    "        frm.destroy()\n",
    "        login_frame()\n",
    "    \n",
    "    lbl_user=Label(frm,text=\"Username\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_pass=Label(frm,text=\"Password\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_mob=Label(frm,text=\"Mobile\",font=('cambria',15,'bold'),fg='blue')\n",
    "    lbl_email=Label(frm,text=\"Email\",font=('cambria',15,'bold'),fg='blue')\n",
    "    \n",
    "    e_user=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    e_user.focus()\n",
    "    e_pass=Entry(frm,font=('cambria',15,'bold'),bd=3,show=\"*\")\n",
    "    e_mob=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    e_email=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "        \n",
    "    lbl_user.place(x=200,y=60)\n",
    "    e_user.place(x=370,y=60)\n",
    "    lbl_pass.place(x=200,y=120)\n",
    "    e_pass.place(x=370,y=120)\n",
    "    lbl_mob.place(x=200,y=180)\n",
    "    e_mob.place(x=370,y=180)\n",
    "    lbl_email.place(x=200,y=240)\n",
    "    e_email.place(x=370,y=240)\n",
    "\n",
    "    btn_update=Label(frm,image=imgtk11)\n",
    "    btn_update.place(x=270,y=320)\n",
    "    btn_update.bind(\"<Button>\",update_todb)\n",
    "    \n",
    "    btn_reset=Label(frm,image=imgtk4)\n",
    "    btn_reset.place(x=460,y=320)\n",
    "\n",
    "    lbl_wel=Label(frm,text=f\"Welcome,{loginuser_row[0]}\",font=('cambria',15,'bold'),fg='green')\n",
    "    lbl_wel.place(x=0,y=0)\n",
    "    \n",
    "    btn_logout=Label(frm,image=imgtk5)\n",
    "    btn_logout.place(relx=.83,rely=.01)\n",
    "    btn_logout.bind(\"<Button>\",logout)\n",
    "    \n",
    "    btn_back=Label(frm,image=imgtk8)\n",
    "    btn_back.place(relx=0,rely=.12)\n",
    "    btn_back.bind(\"<Button>\",back)\n",
    "    \n",
    "    con=sqlite3.connect(database=\"carpool.sqlite\")\n",
    "    cursor=con.cursor()\n",
    "    cursor.execute(\"select mobile,email,password from users where username=?\",(loginuser_row[0],))\n",
    "    row=cursor.fetchone()\n",
    "    e_user.configure(state=\"normal\")\n",
    "    e_user.delete(0,\"end\")\n",
    "    e_user.insert(0,loginuser_row[0])\n",
    "    e_user.configure(state=\"disabled\")\n",
    "    \n",
    "    e_pass.delete(0,\"end\")\n",
    "    e_pass.insert(0,row[2])\n",
    "    \n",
    "    e_mob.delete(0,\"end\")\n",
    "    e_mob.insert(0,row[0])\n",
    "    \n",
    "    e_email.delete(0,\"end\")\n",
    "    e_email.insert(0,row[1])\n",
    "    con.close()\n",
    "    \n",
    "home_frame()\n",
    "win.mainloop()\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9725848-fad0-476d-a498-49a896a1316c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "baff95b6-8f05-4434-a24d-4b248da45bc7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
